version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx api_docs/tf_quant_finance"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
      - jupyter-book sphinx

sphinx:
  configuration: api_docs/tf_quant_finance/conf.py
  builder: html
  fail_on_warning: true