name: Run Tests & Calculate Coverage

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run the tests
      uses: addnab/docker-run-action@v3
      with:
        image: paolodelia99/tf-quant-finance-dev:py3.12
        options: -v ${{ github.workspace }}:/workspace
        shell: bash
        run: |
            source scripts/run_tests.sh --cov
    
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        format: cobertura
        file: coverage.xml
